using UnityEngine;
using UnityEngine.UI;

public class PasswordTrigger : MonoBehaviour
{
    public GameObject passwordPanel; // í‚¤íŒ¨ë“œ UI
    public GameObject interactionUI;     // "F í‚¤ë¥¼ ëˆŒëŸ¬ ìƒí˜¸ì‘ìš©í•˜ì„¸ìš”" í…ìŠ¤íŠ¸
    private bool isPlayerNear = false;

    void Update()
    {
        if (isPlayerNear)
        {

            if (Input.GetKeyDown(KeyCode.F))
            {
                passwordPanel.SetActive(true); // í‚¤íŒ¨ë“œ ì—´ê¸°
                Time.timeScale = 0f; // (ì„ íƒì‚¬í•­) ê²Œì„ ì¼ì‹œì •ì§€
            }
        }
        else
        {
            interactionUI.SetActive(false); // ë©€ì–´ì§€ë©´ ë©”ì‹œì§€ ë„ê¸°
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            isPlayerNear = true;
            interactionUI.SetActive(true); // ğŸ‘‰ ì—¬ê¸° ì¶”ê°€!
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            isPlayerNear = false;
            interactionUI.SetActive(false);
        }
    }
}